### PR TITLE
Add module for keeping track of logged in users

### PR DESCRIPTION
**Pull request by itensionanders**
Getting the login data directly from utmp(5), both total users and unique usernames

### CODE REVIEW

**Comment by dpocock** [comment]
Should this work for any UNIX other than Linux?

Has there been any discussion on the mailing list, if so, could you provide a link to the archive?  In particular, could you check on the mailing list if people are satisfied with the metric names and if nobody complains, we go with the names you chose.

**Comment by itensionanders** [comment]
Will post on the list, it has not been tested for other UNIX (but no reason why it *shouldn't work)

**Comment by itensionanders** [comment]
@dpocock: https://sourceforge.net/p/ganglia/mailman/message/35034472/

**Comment by dpocock** [comment]
I added a section to the README "When does a module belong in ganglia-modules-linux?" to try and help us work out whether this belongs in ganglia-modules-linux or in https://github.com/ganglia/monitor-core

**Comment by itensionanders** [comment]
According to utmp(5) and libmetrics, if I want to include the module in monitor-core I need to:
- Port the code from utmp(5) to utmpx(5)
- Copy that code to half a dozen other OS
- Write an implementation for MinGW/Win32

All is doable, but it it's more and different work than just adding a loadable module here...

**Comment by dpocock** [comment]
OK, so we accept it here for now and we can review those policies in gmond at some time in future, they may be a bit too strict.

**Comment by dpocock** [comment]
Please ping me next week to make a ganglia-modules-linux release with this new module, I'm leaving shortly for Linuxwochen.at and can't do the release now.

**Pull request merged**
